name: Download repo file

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: suisei-cn/actions-download-file@v1.0.1
         id: downloadfile  # Remember to give an ID if you need the output
         name: Download the file
         with:
          url: "https://download-gcdn.ej-technologies.com/install4j/install4j_linux-x64_9_0_6.deb"
          target: public/
          auto-match: true
          
 #       uses: dsaltares/fetch-gh-release-asset@master
 #       with:
 #         repo: 'microsoft/mssql-jdbc'
 #         version: 'tags/v11.2.1'
 #         file: 'mssql-jdbc_auth.zip'
 #         target: 'subdir/mssql-jdbc_auth.zip'
 #         token: ${{ secrets.GITHUB_TOKEN }}
  
  
#     - name: Create file
#       uses: microsoft/mssql-jdbc/fetch-gh-release-asset@master
#       with:
#          repo: 'microsoft/mssql-jdbc/releases'
#          version: 'tags/latest'
#          file: 'mssql-jdbc_auth.zip'
#          token: ${{ secrets.GITHUB_TOKEN }}
