name: Download repo file

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        uses: suisei-cn/actions-download-file@v1.0.1
        id: downloadfile  # Remember to give an ID if you need the output
      - name: Download the file
        with:
          url: "https://cdn.jsdelivr.net/npm/workbox-sw@5.1.3/build/workbox-sw.min.js"
          target: public/
          auto-match: true
          
 #       uses: dsaltares/fetch-gh-release-asset@master
 #       with:
 #         repo: 'microsoft/mssql-jdbc'
 #         version: 'tags/v11.2.1'
 #         file: 'mssql-jdbc_auth.zip'
 #         target: 'subdir/mssql-jdbc_auth.zip'
 #         token: ${{ secrets.GITHUB_TOKEN }}
  
  
#     - name: Create file
#       uses: microsoft/mssql-jdbc/fetch-gh-release-asset@master
#       with:
#          repo: 'microsoft/mssql-jdbc/releases'
#          version: 'tags/latest'
#          file: 'mssql-jdbc_auth.zip'
#          token: ${{ secrets.GITHUB_TOKEN }}
