name: Download repo file

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download mssql dll
        run: |
          wget https://github.com/microsoft/mssql-jdbc/releases/download/v11.2.1/mssql-jdbc_auth.zip
          sudo dpkg -i mssql-jdbc_auth.zip
          dpkg -L mssql-jdbc_auth
     
          
 #       uses: dsaltares/fetch-gh-release-asset@master
 #       with:
 #         repo: 'microsoft/mssql-jdbc'
 #         version: 'tags/v11.2.1'
 #         file: 'mssql-jdbc_auth.zip'
 #         target: 'subdir/mssql-jdbc_auth.zip'
 #         token: ${{ secrets.GITHUB_TOKEN }}
  
  
#     - name: Create file
#       uses: microsoft/mssql-jdbc/fetch-gh-release-asset@master
#       with:
#          repo: 'microsoft/mssql-jdbc/releases'
#          version: 'tags/latest'
#          file: 'mssql-jdbc_auth.zip'
#          token: ${{ secrets.GITHUB_TOKEN }}
