name: Download repo file

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download mssql dll
        run: |
           wget https://github.com/microsoft/mssql-jdbc/releases/download/v11.2.1/mssql-jdbc_auth.zip
           7z x mssql-jdbc_auth.zip
           ls mssql-jdbc_auth
           cp -f mssql-jdbc_auth/x64/mssql-jdbc_auth-11.2.1.x64.dll src
           pwd
           git init
           git config --global user.email "subhamita@technoexponent.com"
           git config --global user.name "subhamita210"
           git config --global init.defaultBranch main
           git branch -m main
           git remote add origin git@github.com:subhamita210/SubhamitaSonarTest.git
           git diff-index --quiet HEAD || git commit -m "Automatic publish from github.com/project"
           git push -u origin main
           
 #     - name: Commit files
 #       run: |
 #         git config --global user.email "subhamita@technoexponent.com"
 #         git config --global user.name "subhamita210"
 #         git commit -m "Add changes" -a
 #     - name: Push changes
 #       uses: ad-m/github-push-action@master
 #       with:
 #         github_token: ${{ secrets.GITHUB_TOKEN }}
     
          
 #       uses: dsaltares/fetch-gh-release-asset@master
 #       with:
 #         repo: 'microsoft/mssql-jdbc'
 #         version: 'tags/v11.2.1'
 #         file: 'mssql-jdbc_auth.zip'
 #         target: 'subdir/mssql-jdbc_auth.zip'
 #         token: ${{ secrets.GITHUB_TOKEN }}
  
  
#     - name: Create file
#       uses: microsoft/mssql-jdbc/fetch-gh-release-asset@master
#       with:
#          repo: 'microsoft/mssql-jdbc/releases'
#          version: 'tags/latest'
#          file: 'mssql-jdbc_auth.zip'
#          token: ${{ secrets.GITHUB_TOKEN }}
