name: Download repo file

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     # - name: Extract branch name
       # shell: bash
      #  run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        #id: extract_branch
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Download mssql dll
        run: |
           wget https://github.com/microsoft/mssql-jdbc/releases/download/v11.2.1/mssql-jdbc_auth.zip
           7z x mssql-jdbc_auth.zip
           ls mssql-jdbc_auth
           cp -f mssql-jdbc_auth/x64/mssql-jdbc_auth-11.2.1.x64.dll sub/mssql-jdbc_auth-11.2.1.x64.dll
           pwd
           ls sub/
           pwd

           
     # - uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
     #     file_pattern: 'src/*'
     #     commit_message: Apply php-cs-fixer changes
           
 #     - name: Commit files
 #       run: |
 #         git config --global user.email "subhamita@technoexponent.com"
 #         git config --global user.name "subhamita210"
 #         git commit -m "Add changes" -a
 #     - name: Push changes
 #       uses: ad-m/github-push-action@master
 #       with:
 #         github_token: ${{ secrets.GITHUB_TOKEN }}
     
          
 #       uses: dsaltares/fetch-gh-release-asset@master
 #       with:
 #         repo: 'microsoft/mssql-jdbc'
 #         version: 'tags/v11.2.1'
 #         file: 'mssql-jdbc_auth.zip'
 #         target: 'subdir/mssql-jdbc_auth.zip'
 #         token: ${{ secrets.GITHUB_TOKEN }}
  
  
#     - name: Create file
#       uses: microsoft/mssql-jdbc/fetch-gh-release-asset@master
#       with:
#          repo: 'microsoft/mssql-jdbc/releases'
#          version: 'tags/latest'
#          file: 'mssql-jdbc_auth.zip'
#          token: ${{ secrets.GITHUB_TOKEN }}
