name: Download repo file

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Create file
       uses: dsaltares/fetch-gh-release-asset@master
       with:
          repo: 'dsaltares/godot-wild-jam-18'
          version: 'tags/v0.1.18'
          file: 'plague-linux.zip'
          target: 'plague-linux.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
