name: Download repo file

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Create file
       uses: dsaltares/fetch-gh-release-asset@master
       with:
          repo: 'https://github.com/microsoft/mssql-jdbc'
          version: 'tags/latest'
          file: 'mssql-jdbc_auth.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
